default: &default
  adapter: postgresql
  username: postgres

development:
  <<: *default
  database: freeletics_core_payment_rails

test:
  <<: *default
  database: freeletics_core_payment_rails_test
