language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1

addons:
  postgresql: "9.4"

before_script:
  - pg_config --version
  - cp config/secrets.yml.example config/secrets.yml
  - psql -c "create database freeletics_running_backend_rails;" -U postgres
  - psql -c "create database freeletics_running_backend_rails_test;" -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=development
