development:
  secret_key_base: "56e0650a26fec9a3898730146c3a8a5e61f2e339da575d8e7a0bf1c48e96e5c20af8d738e58a0a02b8aa35a7d1a8a582a4d8adc0704c79f5a1fa642535d3d088"
  api_rsa_key_private: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzui982bN7C7y1mNgIsNBVFc92bOZdkh1Wbihzq5Gbrw7mwmF
    yIsQRm8fyGm/5jsTgUcAfkjE9SUA7qr5lpcEmYJNzWHqfIi2ngwXzVC36c02aWV1
    lGAEzJtfK0gqzTUR8dJgcvoY2ia5YFFHq53frrEm/DAByr4UGZRtKQDRK2QwXo9L
    Jw1KbO68N+Tt/6CWklkoM5pVgS2xA3yMg023sGlPrrT5Z9QyVpdAOIubWQUoBEZN
    q1c2E2LUHKFmrJgIUd4ZSyfNko25k8abfJE7puywtpKg4PTtKIkFxqi8lvtmF94K
    dnEN/K9dyLCaE+vRSPlfbH5TRD7UDfQ8qZc/7wIDAQABAoIBAA8Zv1s3QoodNw3c
    fNSsqWTtZQ8xY17VlPLyXaTG5U8Jn9QF0uS6+XoafBhVV3MHFrpVozyUNQOrKrFA
    eyy5YtWNQ/5cSg/CrolEWqxaWsHOf00b4YPtqgwAvuZawvztBZ0/fFiH1i59qwPT
    isaEpCGMvkqjek4Ap1jik0Dt1VY0PROKxOGKP27ViWm8mBGqyI7xeWRSqrWMRo6X
    xbrOPNbRJ5QLSa1BkYRyJaHo7woX+iBMn2Zswu7l4JP9UP/Q/bQL0C/ZBRHSalGd
    NLZIHwPDsUyzW8Je9T/7Cdc+y4U8c1870evQuKgP+qsiu8o43DyXGdqTfd51pi3z
    yUaWB8kCgYEA7S7+3OaLPhDK9o3dA1oKD7L8kAQ3frRyRQu+R2wjEBCvzu9xAH8y
    Nzx1rIQPZOcKjLO7/e1lzbjOCUhYKEQWO63SEKAEZHW1iGsDzf0hZrf6D6AKUjYR
    nn5y01M9T/7P2/sIv4zyYcwgr2qeMjeUiLGFMRom1P1T8lPWQ2cRi60CgYEA31Ll
    xuxBjfzsk6i++aw7lFJGCxwPqase3JZCqxL+W1nS9WqZdprZ0T8Udaz2Ma4jRbd6
    bmh1Uojjf75moOIcj000icisAWTOjOVY+HNZfzIieayTTvMa/ctqgVQTH7vfE4XV
    tmfT9n20DfQFgrtIU3x10P64c/MgXtTTq/PvLYsCgYAsBNPSJYtkGnPArHV/QL+r
    SDmtdMrj3hNzEwnecYhUW/R1AGVFhVXJgJQKT3wX6vU/RcA3EU8ajhjXCjEqT/Cc
    ZNcetMP77Qii59GN8lO3n59uNPKVbWl5s9gVtlYjuZPULNPj0QHO+rZ6N9xiT4Rm
    liO1CDh6wQVKbRrP6ZoNBQKBgQCjIqlbcMZKdJJVIxWuyRQUuy0TfIIsjSZUOSem
    VI+eJ7WlNSO5slCfPBc0Bw8pJ234xZkYAhKCIiEd9fZ+W+5E+D8Cz6Zmtj70Sa1+
    gLTF59erTleleo0jDG9W3hXCPrksR73gK2R5UUYwUyubXjftVKOz8f7IJLhmzc16
    dQ0pFQKBgQDI43e68Y5W4+nBcjZ6kRShriyqF3JQaE97nUf3TlLEvAZWl0QAvr8t
    PlC7B5A4I8v2PosVn96MF0urz4+ceFIZbu56wyU45eeY+908TzfoJ2Drm/qgTA3h
    Uyma31bFm4gdBxhFxJZo/eRHRbfl6XClCK5lYDgG+Dqnr6X2aDxB5w==
    -----END RSA PRIVATE KEY-----

test:
  secret_key_base: "93d7d171e5eb59b505d88d440e038a362224c0a0d5f2b00761e1a1998e2f5a156fadb7d79bd4374f594f2fe389032ac69fad6b0b6fb722064f0d59d8e82bf31d"
  api_rsa_key_private: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzui982bN7C7y1mNgIsNBVFc92bOZdkh1Wbihzq5Gbrw7mwmF
    yIsQRm8fyGm/5jsTgUcAfkjE9SUA7qr5lpcEmYJNzWHqfIi2ngwXzVC36c02aWV1
    lGAEzJtfK0gqzTUR8dJgcvoY2ia5YFFHq53frrEm/DAByr4UGZRtKQDRK2QwXo9L
    Jw1KbO68N+Tt/6CWklkoM5pVgS2xA3yMg023sGlPrrT5Z9QyVpdAOIubWQUoBEZN
    q1c2E2LUHKFmrJgIUd4ZSyfNko25k8abfJE7puywtpKg4PTtKIkFxqi8lvtmF94K
    dnEN/K9dyLCaE+vRSPlfbH5TRD7UDfQ8qZc/7wIDAQABAoIBAA8Zv1s3QoodNw3c
    fNSsqWTtZQ8xY17VlPLyXaTG5U8Jn9QF0uS6+XoafBhVV3MHFrpVozyUNQOrKrFA
    eyy5YtWNQ/5cSg/CrolEWqxaWsHOf00b4YPtqgwAvuZawvztBZ0/fFiH1i59qwPT
    isaEpCGMvkqjek4Ap1jik0Dt1VY0PROKxOGKP27ViWm8mBGqyI7xeWRSqrWMRo6X
    xbrOPNbRJ5QLSa1BkYRyJaHo7woX+iBMn2Zswu7l4JP9UP/Q/bQL0C/ZBRHSalGd
    NLZIHwPDsUyzW8Je9T/7Cdc+y4U8c1870evQuKgP+qsiu8o43DyXGdqTfd51pi3z
    yUaWB8kCgYEA7S7+3OaLPhDK9o3dA1oKD7L8kAQ3frRyRQu+R2wjEBCvzu9xAH8y
    Nzx1rIQPZOcKjLO7/e1lzbjOCUhYKEQWO63SEKAEZHW1iGsDzf0hZrf6D6AKUjYR
    nn5y01M9T/7P2/sIv4zyYcwgr2qeMjeUiLGFMRom1P1T8lPWQ2cRi60CgYEA31Ll
    xuxBjfzsk6i++aw7lFJGCxwPqase3JZCqxL+W1nS9WqZdprZ0T8Udaz2Ma4jRbd6
    bmh1Uojjf75moOIcj000icisAWTOjOVY+HNZfzIieayTTvMa/ctqgVQTH7vfE4XV
    tmfT9n20DfQFgrtIU3x10P64c/MgXtTTq/PvLYsCgYAsBNPSJYtkGnPArHV/QL+r
    SDmtdMrj3hNzEwnecYhUW/R1AGVFhVXJgJQKT3wX6vU/RcA3EU8ajhjXCjEqT/Cc
    ZNcetMP77Qii59GN8lO3n59uNPKVbWl5s9gVtlYjuZPULNPj0QHO+rZ6N9xiT4Rm
    liO1CDh6wQVKbRrP6ZoNBQKBgQCjIqlbcMZKdJJVIxWuyRQUuy0TfIIsjSZUOSem
    VI+eJ7WlNSO5slCfPBc0Bw8pJ234xZkYAhKCIiEd9fZ+W+5E+D8Cz6Zmtj70Sa1+
    gLTF59erTleleo0jDG9W3hXCPrksR73gK2R5UUYwUyubXjftVKOz8f7IJLhmzc16
    dQ0pFQKBgQDI43e68Y5W4+nBcjZ6kRShriyqF3JQaE97nUf3TlLEvAZWl0QAvr8t
    PlC7B5A4I8v2PosVn96MF0urz4+ceFIZbu56wyU45eeY+908TzfoJ2Drm/qgTA3h
    Uyma31bFm4gdBxhFxJZo/eRHRbfl6XClCK5lYDgG+Dqnr6X2aDxB5w==
    -----END RSA PRIVATE KEY-----
