# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b6fb350e54694295aca46fc1eed5988320c4f3d178b55d03720c750c25f5368ed1d14ab56a2d5f2149ad7afd3e99c83206999afad95e7459b3b8bdde1bc4895
  omniauth_github_client_id: dad9b3c6cb7f5c450385
  omniauth_github_client_secret: 5c8cd2069e2769a2bdc32d8521c52826aa94b487
  vms_root: <%= File.join(Rails.root, 'projects') %>
  railroady_path: <%= File.join(Rails.root, '..', 'railroady', 'bin', 'railroady') %>
  dotojson_path: <%= File.join(Rails.root, 'lib', 'dotojson') %>
  project_json: <%= File.join(Rails.root, 'public', 'project_json') %>
  # ngrok testing
  app_hooks_url: 'http://0ecf9068.ngrok.io/hooks/github_event'
  overrides_path: <%= File.join(Rails.root, 'gc_backups', 'overrides') %>

test:
  secret_key_base: 9b6fb350e54694295aca46fc1eed5988320c4f3d178b55d03720c750c25f5368ed1d14ab56a2d5f2149ad7afd3e99c83206999afad95e7459b3b8bdde1bc4895
  vms_root: <%= File.join(Rails.root, 'test_projects') %>
  project_json: <%= File.join(Rails.root, 'test_public', 'test_project_json') %>
  railroady_path: <%= File.join(Rails.root, '..', 'railroady', 'bin', 'railroady') %>
  dotojson_path: <%= File.join(Rails.root, 'lib', 'dotojson') %>
  # ngrok testing
  app_hooks_url: 'http://0ecf9068.ngrok.io/hooks/github_event'
  overrides_path: <%= File.join(Rails.root, 'gc_backups_test', 'overrides') %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_github_client_id: <%= ENV['OMNIAUTH_GITHUB_CLIENT_ID'] %>
  omniauth_github_client_secret: <%= ENV['OMNIAUTH_GITHUB_CLIENT_SECRET'] %>
  google_analytics_tracking_id: <%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>
  app_hooks_url: 'https://gorgeouscode-alpha.herokuapp.com/hooks/github_event'
