# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:               9b6fb350e54694295aca46fc1eed5988320c4f3d178b55d03720c750c25f5368ed1d14ab56a2d5f2149ad7afd3e99c83206999afad95e7459b3b8bdde1bc4895
  omniauth_github_client_id:     dad9b3c6cb7f5c450385
  omniauth_github_client_secret: 5c8cd2069e2769a2bdc32d8521c52826aa94b487
  vms_root:                      <%= File.join(Rails.root, 'projects') %>
  railroady_path:                <%= File.join(Rails.root, 'vendor', 'railroady', 'bin', 'railroady') %>
  dotojson_path:                 <%= File.join(Rails.root, 'lib', 'dotojson') %>
  project_json:                  <%= File.join(Rails.root, 'public', 'project_json') %>
  app_hooks_url:                 'http://0ecf9068.ngrok.io/hooks/github_event' # ngrok testing
  overrides_path:                <%= File.join(Rails.root, 'overrides') %>
  google_analytics_tracking_id:
  rvm_path: '~/.rvm/scripts/rvm'

test:
  secret_key_base:               9b6fb350e54694295aca46fc1eed5988320c4f3d178b55d03720c750c25f5368ed1d14ab56a2d5f2149ad7afd3e99c83206999afad95e7459b3b8bdde1bc4895
  omniauth_github_client_id:
  omniauth_github_client_secret:
  vms_root:                      <%= File.join(Rails.root, 'test_projects') %>
  railroady_path:                <%= File.join(Rails.root, 'vendor', 'railroady', 'bin', 'railroady') %>
  dotojson_path:                 <%= File.join(Rails.root, 'lib', 'dotojson') %>
  project_json:                  <%= File.join(Rails.root, 'public', 'project_json') %>
  app_hooks_url:                 'http://0ecf9068.ngrok.io/hooks/github_event' # ngrok testing
  overrides_path:                <%= File.join(Rails.root, 'overrides') %>
  google_analytics_tracking_id:
  rvm_path: '~/.rvm/scripts/rvm'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_github_client_id: <%= ENV['OMNIAUTH_GITHUB_CLIENT_ID'] %>
  omniauth_github_client_secret: <%= ENV['OMNIAUTH_GITHUB_CLIENT_SECRET'] %>
  vms_root: <%= File.join(Rails.root, 'projects') %>
  railroady_path: <%= File.join(Rails.root, 'vender', 'railroady', 'bin', 'railroady') %>
  dotojson_path: <%= File.join(Rails.root, 'lib', 'dotojson') %>
  project_json: <%= File.join(Rails.root, 'public', 'project_json') %>
  app_hooks_url: 'https://www.gorgeouscode.com/hooks/github_event'
  overrides_path: <%= File.join(Rails.root, 'overrides') %>
  google_analytics_tracking_id: <%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>
  rvm_path: <%= ENV['RVM_PATH'] %>
