default: &default
  adapter: postgresql
  username: postgres

development:
  <<: *default
  database: freeletics_core_user_rails

test:
  <<: *default
  database: freeletics_core_user_rails_test

core-admin:
  test:
    <<: *default
    database: freeletics_core_user_rails_core_admin_test
