language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1

addons:
  postgresql: '9.4'

before_script:
  - pg_config --version
  - cp config/secrets.yml.example config/secrets.yml
  - psql -c 'create database freeletics_fl_backend_rails;' -U postgres
  - psql -c 'create database freeletics_fl_backend_rails_test;' -U postgres
  - psql -c 'create database freeletics_fl_backend_rails_core_user_test;' -U postgres
  - bin/rake db:structure:load RAILS_ENV=development
