default: &default
  adapter: postgresql
  username: postgres

development:
  <<: *default
  database: freeletics_nutrition_backend_rails

test:
  <<: *default
  database: freeletics_nutrition_backend_rails_test
